
import React, { useState } from 'react';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import TextAnalyzer from '@/components/TextAnalyzer';
import ResultsDisplay from '@/components/ResultsDisplay';
import { Loader2 } from 'lucide-react';
import modelService from '@/services/modelService';
import { toast } from "@/components/ui/use-toast";

const TextDetection = () => {
  const [showResults, setShowResults] = useState(false);
  const [aiProbability, setAiProbability] = useState(0);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const handleTextAnalyze = async (text: string) => {
    try {
      setIsAnalyzing(true);
      console.log('Analyzing text sample');
      
      // Process the text
      const probability = await modelService.analyzeText(text);
      
      setAiProbability(probability);
      setShowResults(true);
      toast({
        title: "Analysis Complete",
        description: "We've processed your text and generated results.",
      });
    } catch (error) {
      console.error('Error analyzing text:', error);
      toast({
        title: "Processing Error",
        description: "There was an error analyzing your text. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-1 pt-28">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto">
            <div className="mb-10 text-center">
              <h1 className="text-3xl font-bold mb-2">Text Detection</h1>
              <p className="text-muted-foreground">
                Paste text to analyze whether it was generated by AI
              </p>
            </div>
            
            {isAnalyzing ? (
              <div className="w-full flex flex-col items-center justify-center py-20">
                <Loader2 className="w-10 h-10 text-primary animate-spin mb-4" />
                <h3 className="text-lg font-medium">Analyzing your text...</h3>
                <p className="text-sm text-muted-foreground mt-2">
                  This may take a moment depending on the length and complexity.
                </p>
              </div>
            ) : (
              <TextAnalyzer onAnalyze={handleTextAnalyze} />
            )}
            
            <ResultsDisplay 
              showResults={showResults} 
              aiProbability={aiProbability} 
              mediaType="text" 
            />
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default TextDetection;
